### ISSUE TITLE
When compressing, zip includes folder named as source

### ISSUE THREAD

**Issue by stan-spotts** [somaz94/compress-decompress#4]
If I use this:

```
 - name: Zip the app contents
        uses: somaz94/compress-decompress@v1
        with:
          command: compress
          source: wwwroot
          format: zip
```
The zip file contents include the folder name itself rather than putting the files in the root of the zip. So we see:

wwwroot/
wwwroot/file1
wwwroot/file2

etc.

But this is what we need:
../
file1
file2

This wreaks havoc when you're using the zip in an Azure App Service zip deploy. It should either not include the folder or there should be a parameter that tells it not to.
